# Generated by Django 5.2.1 on 2025-05-16 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('airline', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('CCM', 'Cabin Crew Member'), ('SCCM', 'Senior Cabin Crew Member')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_flight_hours', models.FloatField()),
                ('flight_pay', models.FloatField()),
                ('basic_salary', models.FloatField()),
                ('housing_allowance', models.FloatField()),
                ('transportation_allowance', models.FloatField()),
                ('total_salary', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('flight_number', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=100)),
                ('reporting_time', models.CharField(max_length=10)),
                ('debriefing_time', models.CharField(max_length=10)),
                ('hours', models.FloatField()),
                ('pay', models.FloatField()),
                ('is_outbound', models.BooleanField(default=False)),
                ('is_turnaround', models.BooleanField(default=False)),
                ('is_layover', models.BooleanField(default=False)),
                ('is_asby', models.BooleanField(default=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
    ]
